# Generated by Django 5.2.5 on 2025-09-07 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtubedl', '0002_alter_playlist_upload_id_alter_track_upload_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this mix', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='mixes/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='mixes/video/')),
                ('info_file', models.FileField(blank=True, null=True, upload_to='mixes/info/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('uploaded', 'Uploaded')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('upload_url', models.URLField(blank=True, help_text='Link to YouTube or other platform', null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('tracks', models.ManyToManyField(related_name='mixes', to='youtubedl.track')),
            ],
        ),
    ]
