# Generated by Django 5.0.1 on 2025-08-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalAPIToken',
        ),
    ]
