# Generated by Django 5.2.5 on 2025-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubedl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='upload_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='upload_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
